### ISSUE TITLE
Quick selection mode needed

### ISSUE THREAD

**Issue by jooyoungseo** [ajrgodfrey/WriteR#3] opened 2018-03-17 01:55 UTC
Hello,

Besides the OS  native selection functionality using Shift key and arrow key combination, having a quick selection mode is required.

The concept is that you press a hotkey at the starting point of your desired selection, and press again the key at the end of the selection. Then, the area between the starting point and the ending point is highlighted as a selected block text for editing.
Hope this could be added in the future.

Thank you very much.

**Comment by marshallflax** [comment] 2018-05-13 13:44
Perhaps something like the following:

1. Control-@ would set a mark at the current insertion point.
2. Alt-control-@ would select the region between the mark and the current insertion point.

Note that the current insertion point stored would be the row/column at the time of the marking so if you mark a location and then change the text before the mark, your mark wouldn't be where you would think it were -- but it's beyond the capabilities of the wx widget to do anything better than that.

Note: I chose Control-@ because that's what emacs has, and alt-control-@ as building upon that.

I think there might be a need for "exchange mark and insertion point", but don't know if it really is needed or what a good command key would be for that.

**Comment by ajrgodfrey** [comment] 2018-05-13 22:55
Sounds promising.

I think I’d choose to modify the Ctrl+@ with shift if it selects some text because selecting with shift is already commonly understood.

There is something that causes the save dialogue to come up if the text was modified , while closing the app after reviewing the text without modification doesn’t ask to save. There is a flag that ought to be set when an explicit save is done to stop the save dialogue coming up when no modifications have been made since the last save.

I raise this because if the save processes can track modification, then surely the marker placement could do so as well (using a different flag of course). If the text has been modified, then the flag would stop the selection from happening.

What do you think?

**Comment by marshallflax** [comment] 2018-05-13 23:37
I actually wasn't able to get shift-@ working (I don't know enough wx to understand why) -- but the @ is already a shifted 2 keystroke, so I wouldn't actually be able to do control-shift-@ in any case.

Instead, I tried control-space and alt-control-space, but happy to try switching to control-space and shift-control-space.  Control-space is actually the corresponding keystroke in emacs -- but again it's easy to switch.

As far as the problem of the "mark" moving out from under you, I certainly could use the IsModified() method of the TextCtrl.  But I'm not sure if that would be overly conservative...I can easily imagine a scenario in which I set a mark, then move *forward* towards what I imagine would be the end of my selection and make some small changes there before performing the "select to mark" command -- and in the cases in which all modifications are *after* the mark, I would not expect and unexpected behavior.

I do wonder which way the original requestor would imagine is best, since I believe he's getting a doctorate in UI's and related accessibility issues.

**Comment by ajrgodfrey** [comment] 2018-05-13 23:56
Wrt to the use of Ctrl+@: I use the Ctrl+( hot key and the Ctrl+4 ($) for different tasks

I assumed the Ctrl+@ was actually just Ctrl+2. Once the PR can be merged I’ll investigate further.


I expect JYS will see your work and be able to comment in due course. He’ll get the notification of me closing the issues he raised if he hasn’t seen things already.

**Closed as completed** 2018-05-26 23:46 UTC
